### ISSUE TITLE
Redirect Inconsistency: View Button Links to Projects Page Instead of Specific Project Details

### ISSUE THREAD

**Issue by LadityaGogoi** [ohcnetwork/leaderboard#281]
### Description

- When users click on any of the "view" buttons, rather than being redirected to a specific page containing project details, they are directed to the projects page showcasing a comprehensive array of all available projects.

### Solution
- I will create a dynamic page for project details

**Comment by rithviknishad** [comment]
@Lobi29 when you click on the view button of a project, it auto scrolls to the desired project in the `/projects` page.

Was it not scrolling to the desired project for you?

**Comment by Lobi29** [comment]
It's functioning well on my device.

However, by incorporating a dynamic page for specific project details, such as projects/[id], we can distinctly separate the project page from the projects page. 

This way, in the future, we can modify the projects page according to our needs without affecting the specific project page. 

Integrating a dynamic page for specific project details will definitely reduce the loading time. By focusing on just one project instead of loading all the projects at once, we can optimize the performance significantly.

**Comment by rithviknishad** [comment]
The idea of `/projects` page is to allow contributors to quickly get an idea of all the active ongoing projects in this organization. I don't think there's so much content on the `/projects` page enough to be concerned about load times.

Maybe we could add filters on top (filter by project category / repository) or `/projects` could show a minimal view of projects grouped by the repository.

**Comment by Lobi29** [comment]
yes, it will be a great enhancement 😮, I will update you, when I am ready with figma design for this page and filter project feature,

**Comment by Lobi29** [comment]
Hey @rithviknishad 
In order to enhance this feature effectively, I am tasked with bridging both the frontend and backend components, seamlessly integrating them. 🤔
Could you please provide me with any architecture and documentation of our website? 🙏
This insight will empower me to implement my ideas and strategies in alignment with our organization's objectives.👍
